spring.application.name=auth-service
server.port=8086

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=myVerySecretJwtKeyThatIsLongEnough12345678901234567890
app.jwt.expiration=3600000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate=DEBUG