INSERT INTO generic_product (name, category_id, image_url)
SELECT v.name, c.id, NULL
FROM (VALUES
    ('Cottage Cheese', 'DAIRY'),
    ('Skyr Yogurt', 'DAIRY'),
    ('White Cheese', 'DAIRY'),
    ('Sour Cream', 'DAIRY'),
    ('Heavy Cream', 'DAIRY'),
    ('Whipping Cream', 'DAIRY'),
    ('Cream Cheese', 'DAIRY'),
    ('Bulgarian Cheese', 'DAIRY'),
    ('Yellow Cheese', 'DAIRY'),
    ('Mozzarella', 'DAIRY'),
    ('Parmesan', 'DAIRY'),
    ('Feta Cheese', 'DAIRY'),
    ('Goat Cheese', 'DAIRY'),
    ('Ricotta', 'DAIRY'),
    ('Camembert', 'DAIRY'),
    ('Brie', 'DAIRY'),
    ('Labneh', 'DAIRY'),
    ('Greek Yogurt', 'DAIRY'),
    ('Natural Yogurt', 'DAIRY'),
    ('Fruit Yogurt', 'DAIRY'),
    ('Butter', 'DAIRY'),
    ('Salted Butter', 'DAIRY'),
    ('Unsalted Butter', 'DAIRY'),
    ('Margarine', 'DAIRY'),
    ('Chocolate Milk', 'DAIRY'),
    ('Lactose-Free Milk', 'DAIRY'),
    ('Soy Milk', 'DAIRY'),
    ('Almond Milk', 'DAIRY'),
    ('Oat Milk', 'DAIRY'),
    ('Kefir', 'DAIRY'),
    ('Vanilla Yogurt', 'DAIRY'),
    ('Probiotic Yogurt', 'DAIRY'),
    ('Sliced Cheese', 'DAIRY'),
    ('Shredded Mozzarella', 'DAIRY'),
    ('Pizza Cheese', 'DAIRY'),
    ('Mineral Water', 'BEVERAGES'),
    ('Sparkling Water', 'BEVERAGES'),
    ('Soda Water', 'BEVERAGES'),
    ('Cola', 'BEVERAGES'),
    ('Diet Cola', 'BEVERAGES'),
    ('Orange Juice', 'BEVERAGES'),
    ('Apple Juice', 'BEVERAGES'),
    ('Grape Juice', 'BEVERAGES'),
    ('Lemonade', 'BEVERAGES'),
    ('Iced Tea', 'BEVERAGES'),
    ('Green Tea', 'BEVERAGES'),
    ('Black Tea', 'BEVERAGES'),
    ('Herbal Tea', 'BEVERAGES'),
    ('Coffee', 'BEVERAGES'),
    ('Instant Coffee', 'BEVERAGES'),
    ('Ground Coffee', 'BEVERAGES'),
    ('Espresso Capsules', 'BEVERAGES'),
    ('Hot Chocolate Mix', 'BEVERAGES'),
    ('Energy Drink', 'BEVERAGES'),
    ('Sports Drink', 'BEVERAGES'),
    ('Tonic Water', 'BEVERAGES'),
    ('Ginger Ale', 'BEVERAGES'),
    ('Beer', 'BEVERAGES'),
    ('Red Wine', 'BEVERAGES'),
    ('White Wine', 'BEVERAGES'),
    ('Rose Wine', 'BEVERAGES'),
    ('Whiskey', 'BEVERAGES'),
    ('Vodka', 'BEVERAGES'),
    ('Arak', 'BEVERAGES'),
    ('Drink Syrup', 'BEVERAGES'),
    ('Baking Powder', 'PANTRY'),
    ('Baking Soda', 'PANTRY'),
    ('Self-Rising Flour', 'PANTRY'),
    ('Whole Wheat Flour', 'PANTRY'),
    ('Cornstarch', 'PANTRY'),
    ('Breadcrumbs', 'PANTRY'),
    ('Panko', 'PANTRY'),
    ('Rice', 'PANTRY'),
    ('Basmati Rice', 'PANTRY'),
    ('Jasmine Rice', 'PANTRY'),
    ('Brown Rice', 'PANTRY'),
    ('Pasta', 'PANTRY'),
    ('Spaghetti', 'PANTRY'),
    ('Penne', 'PANTRY'),
    ('Fusilli', 'PANTRY'),
    ('Couscous', 'PANTRY'),
    ('Bulgur', 'PANTRY'),
    ('Quinoa', 'PANTRY'),
    ('Oats', 'PANTRY'),
    ('Rolled Oats', 'PANTRY'),
    ('Granola', 'PANTRY'),
    ('Honey', 'PANTRY'),
    ('Maple Syrup', 'PANTRY'),
    ('Jam', 'PANTRY'),
    ('Peanut Butter', 'PANTRY'),
    ('Chocolate Spread', 'PANTRY'),
    ('Olive Oil', 'PANTRY'),
    ('Canola Oil', 'PANTRY'),
    ('Sunflower Oil', 'PANTRY'),
    ('Vinegar', 'PANTRY'),
    ('Apple Cider Vinegar', 'PANTRY'),
    ('Soy Sauce', 'PANTRY'),
    ('Teriyaki Sauce', 'PANTRY'),
    ('Sweet Chili Sauce', 'PANTRY'),
    ('Hot Sauce', 'PANTRY'),
    ('Mustard', 'PANTRY'),
    ('BBQ Sauce', 'PANTRY'),
    ('Pesto', 'PANTRY'),
    ('Tomato Sauce', 'PANTRY'),
    ('Pasta Sauce', 'PANTRY'),
    ('Red Lentils', 'PANTRY'),
    ('Green Lentils', 'PANTRY'),
    ('Chickpeas Dry', 'PANTRY'),
    ('Beans Dry', 'PANTRY'),
    ('Black Beans Dry', 'PANTRY'),
    ('Split Peas', 'PANTRY'),
    ('Popcorn Kernels', 'PANTRY'),
    ('Crackers', 'PANTRY'),
    ('Rice Cakes', 'PANTRY'),
    ('Tortillas', 'PANTRY'),
    ('Bread', 'PANTRY'),
    ('Pita Bread', 'PANTRY'),
    ('Bagels', 'PANTRY'),
    ('Matzo', 'PANTRY'),
    ('Semolina', 'PANTRY'),
    ('Cocoa Powder', 'PANTRY'),
    ('Vanilla Extract', 'PANTRY'),
    ('Yeast', 'PANTRY'),
    ('Powdered Sugar', 'PANTRY'),
    ('Sea Salt', 'PANTRY'),
    ('Orange', 'FRUITS'),
    ('Mandarin', 'FRUITS'),
    ('Grapefruit', 'FRUITS'),
    ('Pear', 'FRUITS'),
    ('Peach', 'FRUITS'),
    ('Nectarine', 'FRUITS'),
    ('Plum', 'FRUITS'),
    ('Mango', 'FRUITS'),
    ('Pineapple', 'FRUITS'),
    ('Kiwi', 'FRUITS'),
    ('Grapes', 'FRUITS'),
    ('Watermelon', 'FRUITS'),
    ('Melon', 'FRUITS'),
    ('Strawberry', 'FRUITS'),
    ('Blueberry', 'FRUITS'),
    ('Raspberry', 'FRUITS'),
    ('Blackberry', 'FRUITS'),
    ('Cherry', 'FRUITS'),
    ('Pomegranate', 'FRUITS'),
    ('Avocado', 'FRUITS'),
    ('Coconut', 'FRUITS'),
    ('Date', 'FRUITS'),
    ('Fig', 'FRUITS'),
    ('Passion Fruit', 'FRUITS'),
    ('Papaya', 'FRUITS'),
    ('Guava', 'FRUITS'),
    ('Lychee', 'FRUITS'),
    ('Apricot', 'FRUITS'),
    ('Persimmon', 'FRUITS'),
    ('Dragon Fruit', 'FRUITS'),
    ('Pomelo', 'FRUITS'),
    ('Cranberry', 'FRUITS'),
    ('Frozen Berries', 'FRUITS'),
    ('Lime', 'FRUITS'),
    ('Green Apple', 'FRUITS'),
    ('Tuna', 'CANNED_FOOD'),
    ('Crushed Tomatoes', 'CANNED_FOOD'),
    ('Tomato Paste', 'CANNED_FOOD'),
    ('Whole Peeled Tomatoes', 'CANNED_FOOD'),
    ('Corn', 'CANNED_FOOD'),
    ('Peas', 'CANNED_FOOD'),
    ('Green Beans', 'CANNED_FOOD'),
    ('Chickpeas', 'CANNED_FOOD'),
    ('White Beans', 'CANNED_FOOD'),
    ('Red Kidney Beans', 'CANNED_FOOD'),
    ('Black Beans', 'CANNED_FOOD'),
    ('Baked Beans', 'CANNED_FOOD'),
    ('Olives', 'CANNED_FOOD'),
    ('Black Olives', 'CANNED_FOOD'),
    ('Green Olives', 'CANNED_FOOD'),
    ('Pickles', 'CANNED_FOOD'),
    ('Pickled Cucumbers', 'CANNED_FOOD'),
    ('Hearts of Palm', 'CANNED_FOOD'),
    ('Mushrooms', 'CANNED_FOOD'),
    ('Artichoke Hearts', 'CANNED_FOOD'),
    ('Roasted Peppers', 'CANNED_FOOD'),
    ('Sauerkraut', 'CANNED_FOOD'),
    ('Coconut Milk', 'CANNED_FOOD'),
    ('Sweet Corn Cream', 'CANNED_FOOD'),
    ('Pineapple Slices', 'CANNED_FOOD'),
    ('Fruit Cocktail', 'CANNED_FOOD'),
    ('Sardines', 'CANNED_FOOD'),
    ('Salmon Can', 'CANNED_FOOD'),
    ('Anchovies', 'CANNED_FOOD'),
    ('Stuffed Vine Leaves', 'CANNED_FOOD'),
    ('Harissa Paste', 'CANNED_FOOD'),
    ('Bean Sprouts', 'CANNED_FOOD'),
    ('Tomato Soup', 'CANNED_FOOD'),
    ('Chicken Soup', 'CANNED_FOOD'),
    ('Evaporated Milk', 'CANNED_FOOD'),
    ('Dish Soap', 'CLEANING'),
    ('Dishwasher Tablets', 'CLEANING'),
    ('Dishwasher Rinse Aid', 'CLEANING'),
    ('Floor Cleaner', 'CLEANING'),
    ('Glass Cleaner', 'CLEANING'),
    ('Bathroom Cleaner', 'CLEANING'),
    ('Toilet Cleaner', 'CLEANING'),
    ('Bleach', 'CLEANING'),
    ('Disinfectant Spray', 'CLEANING'),
    ('Multi-Surface Cleaner', 'CLEANING'),
    ('Degreaser', 'CLEANING'),
    ('Oven Cleaner', 'CLEANING'),
    ('Drain Cleaner', 'CLEANING'),
    ('Sponges', 'CLEANING'),
    ('Scrub Pads', 'CLEANING'),
    ('Garbage Bags', 'CLEANING'),
    ('Paper Towels', 'CLEANING'),
    ('Cleaning Cloths', 'CLEANING'),
    ('Rubber Gloves', 'CLEANING'),
    ('Air Freshener', 'CLEANING'),
    ('Furniture Polish', 'CLEANING'),
    ('Mold Remover', 'CLEANING'),
    ('Limescale Remover', 'CLEANING'),
    ('Disinfecting Wipes', 'CLEANING'),
    ('Hand Sanitizer', 'CLEANING'),
    ('Potato Chips', 'SNACKS'),
    ('Tortilla Chips', 'SNACKS'),
    ('Pretzels', 'SNACKS'),
    ('Popcorn', 'SNACKS'),
    ('Chocolate Bar', 'SNACKS'),
    ('Cookies', 'SNACKS'),
    ('Biscuits', 'SNACKS'),
    ('Wafer Cookies', 'SNACKS'),
    ('Crackers Snack', 'SNACKS'),
    ('Peanuts', 'SNACKS'),
    ('Almonds', 'SNACKS'),
    ('Cashews', 'SNACKS'),
    ('Pistachios', 'SNACKS'),
    ('Trail Mix', 'SNACKS'),
    ('Gummy Candy', 'SNACKS'),
    ('Chewing Gum', 'SNACKS'),
    ('Protein Bar', 'SNACKS'),
    ('Granola Bar', 'SNACKS'),
    ('Halva', 'SNACKS'),
    ('Dried Fruit Mix', 'SNACKS'),
    ('Laundry Detergent', 'LAUNDRY'),
    ('Fabric Softener', 'LAUNDRY'),
    ('Stain Remover', 'LAUNDRY'),
    ('Laundry Capsules', 'LAUNDRY'),
    ('Laundry Powder', 'LAUNDRY'),
    ('Color Catcher Sheets', 'LAUNDRY'),
    ('Delicate Wash', 'LAUNDRY'),
    ('Wool Detergent', 'LAUNDRY'),
    ('Ironing Water', 'LAUNDRY'),
    ('Laundry Sanitizer', 'LAUNDRY'),
    ('Bleach for Laundry', 'LAUNDRY'),
    ('Dryer Sheets', 'LAUNDRY'),
    ('Mesh Laundry Bag', 'LAUNDRY'),
    ('Lint Roller', 'LAUNDRY'),
    ('Clothes Pins', 'LAUNDRY'),
    ('Shampoo', 'PERSONAL_CARE'),
    ('Conditioner', 'PERSONAL_CARE'),
    ('Body Wash', 'PERSONAL_CARE'),
    ('Bar Soap', 'PERSONAL_CARE'),
    ('Face Wash', 'PERSONAL_CARE'),
    ('Face Cream', 'PERSONAL_CARE'),
    ('Body Lotion', 'PERSONAL_CARE'),
    ('Deodorant', 'PERSONAL_CARE'),
    ('Toothpaste', 'PERSONAL_CARE'),
    ('Toothbrush', 'PERSONAL_CARE'),
    ('Mouthwash', 'PERSONAL_CARE'),
    ('Dental Floss', 'PERSONAL_CARE'),
    ('Cotton Pads', 'PERSONAL_CARE'),
    ('Cotton Swabs', 'PERSONAL_CARE'),
    ('Wet Wipes', 'PERSONAL_CARE'),
    ('Baby Wipes', 'PERSONAL_CARE'),
    ('Toilet Paper', 'PERSONAL_CARE'),
    ('Tissues', 'PERSONAL_CARE'),
    ('Razors', 'PERSONAL_CARE'),
    ('Shaving Cream', 'PERSONAL_CARE'),
    ('Sunscreen', 'PERSONAL_CARE'),
    ('Feminine Hygiene Pads', 'PERSONAL_CARE'),
    ('Tampons', 'PERSONAL_CARE'),
    ('Hair Brush', 'PERSONAL_CARE'),
    ('Lip Balm', 'PERSONAL_CARE'),
    ('Carrot', 'VEGETABLES'),
    ('Sweet Potato', 'VEGETABLES'),
    ('Garlic', 'VEGETABLES'),
    ('Bell Pepper', 'VEGETABLES'),
    ('Red Pepper', 'VEGETABLES'),
    ('Green Pepper', 'VEGETABLES'),
    ('Zucchini', 'VEGETABLES'),
    ('Eggplant', 'VEGETABLES'),
    ('Pumpkin', 'VEGETABLES'),
    ('Butternut Squash', 'VEGETABLES'),
    ('Broccoli', 'VEGETABLES'),
    ('Cauliflower', 'VEGETABLES'),
    ('Cabbage', 'VEGETABLES'),
    ('Red Cabbage', 'VEGETABLES'),
    ('Lettuce', 'VEGETABLES'),
    ('Spinach', 'VEGETABLES'),
    ('Celery', 'VEGETABLES'),
    ('Parsley', 'VEGETABLES'),
    ('Cilantro', 'VEGETABLES'),
    ('Mushroom Fresh', 'VEGETABLES')
) AS v(name, category_code)
JOIN product_category c ON c.code = v.category_code;