alter table generic_product
add column is_default_requirement boolean not null default false;

update generic_product
set is_default_requirement = true
where name in (
    'Yellow Cheese',
    'Yeast',
    'White Cheese',
    'Wet Wipes',
    'Vanilla Extract',
    'Tuna',
    'Toothpaste',
    'Tomato Sauce',
    'Tomato Paste',
    'Tahini',
    'Sponges',
    'Spaghetti',
    'Self-Rising Flour',
    'Butter',
    'Pickled Cucumbers',
    'Oats',
    'Mustard',
    'Mayonnaise',
    'Lettuce',
    'Lemon',
    'Ketchup',
    'Honey',
    'Green Tea',
    'Milk',
    'Bread',
    'Toilet Paper',
    'Dish Soap',
    'Garlic',
    'Crushed Tomatoes',
    'Couscous',
    'Corn',
    'Salt',
    'Sugar',
    'Flour',
    'Olive Oil',
    'Cocoa Powder',
    'Chicken Soup',
    'Chewing Gum',
    'Carrot',
    'Canola Oil',
    'Rice',
    'Baking Powder',
    'Pasta',
    'Tomato',
    'Cucumber',
    'Onion',
    'Potato',
    'Air Fresheners'
);